# Generated by Django 3.2.25 on 2025-09-03 14:21

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0190_auto_20250517_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur_Individu',
            fields=[
            ],
            options={
                'verbose_name': 'Individu',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.utilisateur',),
            managers=[
                ('objects', core.models.CustomUserManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='utilisateur',
            options={'permissions': [('famille_resume', 'Fiche famille | Résumé'), ('famille_questionnaire', 'Fiche famille | Questionnaire'), ('famille_questionnaire_modifier', 'Fiche famille | Questionnaire | Modifier'), ('famille_pieces', 'Fiche famille | Pièces'), ('famille_pieces_modifier', 'Fiche famille | Pièces | Modifier'), ('famille_locations', 'Fiche famille | Locations'), ('famille_locations_modifier', 'Fiche famille | Locations | Modifier'), ('famille_cotisations', 'Fiche famille | Adhésions'), ('famille_cotisations_modifier', 'Fiche famille | Adhésions | Modifier'), ('famille_caisse', 'Fiche famille | Caisse'), ('famille_caisse_modifier', 'Fiche famille | Caisse | Modifier'), ('famille_aides', 'Fiche famille | Aides'), ('famille_aides_modifier', 'Fiche famille | Aides | Modifier'), ('famille_quotients', 'Fiche famille | Quotients familiaux'), ('famille_quotients_modifier', 'Fiche famille | Quotients familiaux | Modifier'), ('famille_prestations', 'Fiche famille | Prestations'), ('famille_prestations_modifier', 'Fiche famille | Prestations | Modifier'), ('famille_factures', 'Fiche famille | Factures'), ('famille_factures_modifier', 'Fiche famille | Factures | Modifier'), ('famille_reglements', 'Fiche famille | Règlements'), ('famille_reglements_modifier', 'Fiche famille | Règlements | Modifier'), ('famille_messagerie', 'Fiche famille | Messagerie'), ('famille_messagerie_modifier', 'Fiche famille | Messagerie | Modifier'), ('famille_portail', 'Fiche famille | Portail'), ('famille_portail_modifier', 'Fiche famille | Portail | Modifier'), ('famille_divers', 'Fiche famille | Paramètres'), ('famille_divers_modifier', 'Fiche famille | Paramètres | Modifier'), ('famille_outils', 'Fiche famille | Outils'), ('famille_consommations', 'Fiche famille | Consommations'), ('famille_consommations_modifier', 'Fiche famille | Consommations | Modifier'), ('individu_resume', 'Fiche individuelle | Résumé'), ('individu_identite', 'Fiche individuelle | Identité'), ('individu_identite_modifier', 'Fiche individuelle | Identité | Modifier'), ('individu_questionnaire', 'Fiche individuelle | Questionnaire'), ('individu_questionnaire_modifier', 'Fiche individuelle | Questionnaire | Modifier'), ('individu_liens', 'Fiche individuelle | Liens'), ('individu_liens_modifier', 'Fiche individuelle | Liens | Modifier'), ('individu_coords', 'Fiche individuelle | Coordonnées'), ('individu_coords_modifier', 'Fiche individuelle | Coordonnées | Modifier'), ('individu_scolarite', 'Fiche individuelle | Scolarité'), ('individu_scolarite_modifier', 'Fiche individuelle | Scolarité | Modifier'), ('individu_inscriptions', 'Fiche individuelle | Inscriptions'), ('individu_inscriptions_modifier', 'Fiche individuelle | Inscriptions | Modifier'), ('individu_regimes_alimentaires', 'Fiche individuelle | Régimes alimentaires'), ('individu_regimes_alimentaires_modifier', 'Fiche individuelle | Régimes alimentaires | Modifier'), ('individu_maladies', 'Fiche individuelle | Maladies'), ('individu_maladies_modifier', 'Fiche individuelle | Maladies | Modifier'), ('individu_medical', 'Fiche individuelle | Médical'), ('individu_medical_modifier', 'Fiche individuelle | Médical | Modifier'), ('individu_assurances', 'Fiche individuelle | Assurances'), ('individu_assurances_modifier', 'Fiche individuelle | Assurances | Modifier'), ('individu_portail', 'Fiche individuelle | Portail'), ('individu_portail_modifier', 'Fiche individuelle | Portail | Modifier'), ('individu_contacts', 'Fiche individuelle | Contacts'), ('individu_contacts_modifier', 'Fiche individuelle | Contacts | Modifier'), ('individu_transports', 'Fiche individuelle | Transports'), ('individu_transports_modifier', 'Fiche individuelle | Transports | Modifier'), ('individu_consommations', 'Fiche individuelle | Consommations')]},
        ),
        migrations.AddField(
            model_name='consentement',
            name='individu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.individu', verbose_name='Individu'),
        ),
        migrations.AddField(
            model_name='destinataire',
            name='activites',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.activite', verbose_name='Activites'),
        ),
        migrations.AddField(
            model_name='destinataire',
            name='inscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.inscription', verbose_name='Inscription'),
        ),
        migrations.AddField(
            model_name='famille',
            name='contact_facturation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_facturation', to='core.individu', verbose_name='Contact facturation'),
        ),
        migrations.AddField(
            model_name='individu',
            name='blocage_impayes_off',
            field=models.BooleanField(default=False, help_text="En cochant cette case, vous permettez à cette famille d'accéder aux réservations du portail même s'il y a des impayés et que le paramètre 'blocage si impayés' a été activé dans les paramètres généraux du portail.", verbose_name='Ne jamais appliquer le blocage des réservations si impayés'),
        ),
        migrations.AddField(
            model_name='individu',
            name='certification_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de certification'),
        ),
        migrations.AddField(
            model_name='individu',
            name='internet_actif',
            field=models.BooleanField(default=True, verbose_name='Compte internet activé'),
        ),
        migrations.AddField(
            model_name='individu',
            name='internet_categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='internet_categori', to='core.categoriecompteinternet', verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='individu',
            name='internet_identifiant',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=200, null=True, verbose_name='Identifiant')),
        ),
        migrations.AddField(
            model_name='individu',
            name='internet_mdp',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=200, null=True, verbose_name='Mot de passe')),
        ),
        migrations.AddField(
            model_name='individu',
            name='internet_reservations',
            field=models.BooleanField(default=True, verbose_name='Autoriser les réservations sur le portail'),
        ),
        migrations.AddField(
            model_name='individu',
            name='internet_secquest',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Question'),
        ),
        migrations.AddField(
            model_name='individu',
            name='mobile',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=100, null=True, verbose_name='Portable favori')),
        ),
        migrations.AddField(
            model_name='individu',
            name='utilisateur',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='portailmessage',
            name='individu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.individu', verbose_name='Individu'),
        ),
        migrations.AlterField(
            model_name='adressemail',
            name='adresse',
            field=models.EmailField(help_text="Saisissez l'adresse mail utilisée.", max_length=300, verbose_name="Adresse d'envoi"),
        ),
        migrations.AlterField(
            model_name='portailmessage',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='portailmessage',
            name='date_lecture',
            field=models.DateTimeField(blank=True, db_index=True, max_length=200, null=True, verbose_name='Date de lecture'),
        ),
        migrations.AlterField(
            model_name='portailparametre',
            name='code',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Code'),
        ),
        migrations.AddIndex(
            model_name='portailmessage',
            index=models.Index(fields=['famille'], name='portail_mes_famille_fd123f_idx'),
        ),
        migrations.AddIndex(
            model_name='portailmessage',
            index=models.Index(fields=['individu'], name='portail_mes_individ_e5b04e_idx'),
        ),
        migrations.AddIndex(
            model_name='portailmessage',
            index=models.Index(fields=['structure'], name='portail_mes_structu_e1e078_idx'),
        ),
        migrations.AddIndex(
            model_name='portailmessage',
            index=models.Index(fields=['utilisateur'], name='portail_mes_utilisa_16d110_idx'),
        ),
        migrations.AddIndex(
            model_name='portailmessage',
            index=models.Index(fields=['date_creation'], name='portail_mes_date_cr_58d8e7_idx'),
        ),
        migrations.AddIndex(
            model_name='portailmessage',
            index=models.Index(fields=['date_lecture'], name='portail_mes_date_le_d93ed6_idx'),
        ),
    ]
