# Generated by Django 3.2.25 on 2025-09-08 10:27

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0191_auto_20250903_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='individu',
            name='ent_id',
            field=django_cryptography.fields.encrypt(models.IntegerField(blank=True, null=True, verbose_name='ent_id')),
        ),
    ]
