# Generated by Django 3.2.25 on 2025-09-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0192_auto_20250917_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborateur',
            name='ent_id',
            field=models.CharField(max_length=200, null=True, verbose_name='ent_id'),
        ),
    ]
