# Generated by Django 5.2.6 on 2026-03-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0199_alter_utilisateur_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesmodele',
            name='objet_dette',
            field=models.CharField(blank=True, max_length=450, null=True, verbose_name='Objet dette par défaut'),
        ),
    ]
