# Generated by Django 3.2.25 on 2026-04-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0200_pesmodele_objet_dette'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unite',
            name='dependances',
            field=models.ManyToManyField(blank=True, related_name='unites_dependantes', to='core.Unite', verbose_name='Unités liées'),
        ),
        migrations.AlterField(
            model_name='unite',
            name='incompatibilites',
            field=models.ManyToManyField(blank=True, related_name='unites_incompatibles', to='core.Unite', verbose_name='Incompatibilités'),
        ),
    ]
